import test from "node:test";
import assert from "node:assert/strict";
import {makeMap,makeRandomMap,search,validateMap,bidirectionalDijkstra} from "../src/core.js";

const map=(w,h,cells,start=0,goal=w*h-1)=>({version:1,width:w,height:h,cells,start,goal});

test("empty map shortest entry cost",()=>{const r=search(map(3,3,Array(9).fill(1)));assert.equal(r.cost,4);assert.equal(r.path.length,5)});
test("start already at goal costs zero for all weighted searches",()=>{const m=map(2,2,[1,1,1,1],0,0);for(const a of ["astar","dijkstra","bidijkstra"])assert.equal(search(m,a).cost,0)});
test("unreachable route explicitly returns null cost",()=>{const r=search(map(3,2,[1,0,1,1,0,1]));assert.equal(r.found,false);assert.equal(r.cost,null);assert.deepEqual(r.path,[])});
test("cheapest route is not always fewest moves",()=>{const m=map(4,3,Array(12).fill(1),4,7);m.cells[5]=m.cells[6]=6;const r=search(m);assert.equal(r.cost,5);assert.equal(r.path.length,6)});
test("entry cost of goal is paid",()=>assert.equal(search(map(2,2,[1,0,1,6])).cost,7));
test("wall never appears in a path",()=>{const m=makeMap();for(const x of search(m).path)assert.ok(m.cells[x]>0)});
test("4-way consecutive path cells share one edge",()=>{const m=makeMap(),p=search(m).path;for(let i=1;i<p.length;i++)assert.equal(Math.abs(p[i]%m.width-p[i-1]%m.width)+Math.abs(Math.floor(p[i]/m.width)-Math.floor(p[i-1]/m.width)),1)});
test("sum of path entry costs equals reported cost",()=>{const m=makeMap(),r=search(m);assert.equal(r.cost,r.path.slice(1).reduce((s,i)=>s+m.cells[i],0))});
test("search does not mutate map",()=>{const m=makeMap(),s=JSON.stringify(m);search(m);assert.equal(JSON.stringify(m),s)});
test("A* and Dijkstra agree on presets",()=>{for(const p of ["warehouse","detour","empty","blocked"]){const m=makeMap(p);assert.equal(search(m).cost,search(m,"dijkstra").cost)}});
test("bidirectional Dijkstra matches Dijkstra on presets",()=>{for(const p of ["warehouse","detour","empty","blocked"]){const m=makeMap(p);assert.equal(search(m,"bidijkstra").cost,search(m,"dijkstra").cost)}});
test("bidirectional path cost matches its path",()=>{const m=makeMap();const r=bidirectionalDijkstra(m);assert.equal(r.cost,r.path.slice(1).reduce((s,i)=>s+m.cells[i],0))});
test("seeded weighted grids keep A* Dijkstra and bidirectional equal",()=>{for(let seed=1;seed<=30;seed++){const m=makeRandomMap({width:18,height:10,seed});const d=search(m,"dijkstra").cost;assert.equal(search(m,"astar").cost,d);assert.equal(search(m,"bidijkstra").cost,d)}});
test("diagonal option can shorten an empty route",()=>{const m=map(5,5,Array(25).fill(1));assert.ok(search(m,"astar",{diagonal:true}).path.length<search(m,"astar").path.length)});
test("A* and Dijkstra agree with diagonals",()=>{for(let seed=1;seed<=20;seed++){const m=makeRandomMap({width:16,height:10,seed});assert.equal(search(m,"astar",{diagonal:true}).cost,search(m,"dijkstra",{diagonal:true}).cost)}});
test("bidirectional Dijkstra agrees with diagonals",()=>{for(let seed=1;seed<=20;seed++){const m=makeRandomMap({width:16,height:10,seed});assert.equal(search(m,"bidijkstra",{diagonal:true}).cost,search(m,"dijkstra",{diagonal:true}).cost)}});
test("BFS minimizes steps even when route cost is higher",()=>{const m=map(4,3,Array(12).fill(1),4,7);m.cells[5]=m.cells[6]=6;const cheap=search(m,"astar"),few=search(m,"bfs");assert.ok(few.path.length<cheap.path.length);assert.ok(few.cost>cheap.cost)});
test("BFS and weighted search agree on empty unweighted map",()=>{const m=makeMap("empty");assert.equal(search(m,"bfs").path.length,search(m,"astar").path.length)});
test("random map is deterministic for a seed",()=>assert.deepEqual(makeRandomMap({seed:99}),makeRandomMap({seed:99})));
test("random map guarantees a route corridor",()=>{for(let seed=1;seed<=20;seed++)assert.equal(search(makeRandomMap({seed})).found,true)});
test("validate returns an independent cell array",()=>{const m=makeMap(),v=validateMap(m);v.cells[0]=0;assert.equal(m.cells[0],1)});
test("invalid weights cannot create negative-cost shortcuts",()=>{for(const v of [-1,2,NaN,Infinity,"1"])assert.throws(()=>validateMap(map(2,2,[1,1,1,v])))});
test("invalid dimensions versions and blocked endpoints refused",()=>{for(const m of [null,{...makeMap(),version:2},{...makeMap(),width:100},map(2,2,[0,1,1,1]),map(2,2,[1,1,1])])assert.throws(()=>validateMap(m))});
test("unknown algorithms presets and random bounds refused",()=>{assert.throws(()=>search(makeMap(),"greedy"));assert.throws(()=>makeMap("other"));assert.throws(()=>makeRandomMap({wallRate:.9}))});
test("ties resolve deterministically",()=>assert.deepEqual(search(makeMap("empty")),search(makeMap("empty"))));
